# Generated by Django 6.1.1 on 2026-09-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("url", models.URLField(max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
